spring:
  application:
    name: CodeForge

  datasource:
    url: jdbc:postgresql://localhost:5432/testDB
    username: testUser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret-key: bfjsgsadjfhf7w4f48t7w4ty4786t43gtuyfbfgfy7refgreffg4w7f4f83f3gfrehjcvb